//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_Ticket_Servis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBilet
    {
        public int ID { get; set; }
        public Nullable<bool> IsSilindi { get; set; }
        public Nullable<int> DurumNo { get; set; }
        public Nullable<int> TipNo { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string Baslik { get; set; }
        public string Konu { get; set; }
        public Nullable<System.DateTime> OlusTarih { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string Notlar { get; set; }
        public Nullable<int> DosyaID { get; set; }
    }
}
