//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_Ticket_Servis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirma
    {
        public int ID { get; set; }
        public Nullable<bool> IsSilindi { get; set; }
        public Nullable<int> DurumNo { get; set; }
        public Nullable<int> TipNo { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Ad { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Telefon2 { get; set; }
        public string Mail { get; set; }
        public string VergiNumara { get; set; }
        public string VergiDaire { get; set; }
        public string WebSite { get; set; }
    }
}
