//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_Ticket_Servis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTip
    {
        public int ID { get; set; }
        public string Grup { get; set; }
        public Nullable<int> No { get; set; }
        public string Ad { get; set; }
        public string Sira { get; set; }
        public Nullable<bool> IsAktif { get; set; }
    }
}
